# This workflow will build a Java project with Maven and Docker

name: Java CI with Maven and Docker in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build in Linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn verify -Pdocker
      working-directory: com.examples.hellodockernet
