# This workflow will build a Java project with Maven and Docker

name: Java CI with Maven and Docker in Windows

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 7 * * 0"

jobs:
  build:
    runs-on: windows-latest

    name: Build in Windows
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn package
      working-directory: com.examples.hellodockernet
    - name: Test with Docker
      run: mvn verify -Pdocker
      working-directory: com.examples.hellodockernet
# In Windows running both leads to
# Cannot create docker access object : \\.\pipe\docker_engine (All pipe instances are busy)
#    - name: Test with Docker Compose
#      run: mvn verify -Pdocker-compose
#      working-directory: com.examples.hellodockernet
